---
title: Improving the LD SuSiE model
site: workflowr::wflow_site
output: workflowr::wflow_html
---

We investigate the performance of SuSiE model for summary statistics with various types of covariance (LD) matrices. We consider 5 types of covariance matrices:

1. In-sample LD matrix: Gold standard

2. Out-sample LD matrix: LD matrix $\widehat{R}$ calculated from a out-of-sample data

3. Regularized: $\widehat{R}_{\lambda} = (1-\lambda) * \widehat{R} + \lambda * I$ with $\lambda = 0.1$

4. Truncated SVD: $\tilde{R}$ as presented in the paper
5. TSVD + Reg.: $\tilde{R}_{\lambda} = (1-\lambda) * \tilde{R} + \lambda * I$ with $\lambda = 0.1$


**Analyses:**

+ [Experiments using the Thyroid dataset](Improved_LD_SuSiE_Thyroid_data.html)

+ [Compare Inferred L](Compare_infer_L.html)

+ [Compare LD Matrices](Compare_LD_Mat.html)

+ [Investigate V after every iteration](V_xy_iter_investigate.html)

+ [Investigate V after every iteration, L=2](V_xy_iter_L2.html)

+ [Example of fine-mapping a blood cell trait using SuSiE-RSS](susie_rss_ukbb.html)

+ [Notes on the Wishart and inverse Wishart distributions](wish_vs_invwish.html)

+ [Investigate learn nu](investigate-df-nu.html)

+ [Investigate learn nu with low-rank decomposition](df-nu-low-rank.html)

+ [Investigate rank and Inverse-Wishart likelihood with N3finemapping data](genotype-matrix-rank-investigation.html)

+ [Estimate nu in the matrix F-distribution](nu-matrix-F-distribution.html)

+ [Summarize estimated $\nu$ in various models](summary-learn-nu.html)
